[package]
name = "passman-applet"
description = "COSMIC panel applet showing passman's lock state"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "passman-applet"
path = "src/main.rs"

[dependencies]
passman-secret.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
rev = "43a50cb6f5af18fa6cbea535fb46460a3c5cd573"
default-features = false
features = ["applet", "tokio", "wayland", "a11y"]
